### ISSUE TITLE
SPI Mode2

### ISSUE THREAD

**Issue by gudman83** [jhgorse/libMPSSE-SPI-LabVIEW#1]
Hello, I try to use libMPSSE-SPI-LabVIEW for comunication SPI Mode2, in SPI Init Channel.vi I set "10" and also "2" in the Option 0-7 but I don't see the correct polarity of clock signal, start and end in low position when I use SPI Write.vi. I try to change the ClockRate and work properly, so the problem is the configOptions.
I try to use libMPSSE.dll with C code and work properly with same option (ClockRate:100000, LatencyTimer: 255 and configOptions: 2).
Could you help me to solve this problem?

**Comment by jhgorse** [comment]
@gudman83 what was the issue?

**Comment by gudman83** [comment]
I use before SPI Init Channel.vi and after SPI Change CS.vi (with same optionConfig) and I see the correct polarity of SPI Mode2. Thank you and best regard
